# Generated by Django 5.1 on 2024-08-09 07:28

import django.db.models.deletion
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='UploadFile',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('file', models.FileField(upload_to='media/excel/')),
                ('upload_status', models.CharField(choices=[('initiated', 'Initiated'), ('processing', 'Processing'), ('success', 'Success'), ('failed', 'Failed')], default='initiated', max_length=20)),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='InsuranceData',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('date', models.DateField()),
                ('product', models.CharField(choices=[('All Other miscellaneous', 'All Other miscellaneous'), ('Aviation', 'Aviation'), ('Credit Guarantee', 'Credit Guarantee'), ('Crop Insurance', 'Crop Insurance'), ('Engineering', 'Engineering'), ('Fire', 'Fire'), ('Health-Government schemes', 'Health-Government schemes'), ('Health-Group', 'Health-Group'), ('Health-Retail', 'Health-Retail'), ('Marine Cargo', 'Marine Cargo'), ('Marine Hull', 'Marine Hull'), ('Motor OD', 'Motor OD'), ('Motor TP', 'Motor TP'), ('Overseas Medical', 'Overseas Medical'), ('P.A. ', 'P.A. ')], max_length=100)),
                ('value', models.FloatField()),
                ('name', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='main.name')),
            ],
            options={
                'abstract': False,
            },
        ),
    ]
