# Generated by Django 5.1 on 2024-08-09 03:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0002_uploadfile_insurancedata'),
    ]

    operations = [
        migrations.AddField(
            model_name='uploadfile',
            name='upload_status',
            field=models.CharField(choices=[('initiated', 'Initiated'), ('processing', 'Processing'), ('success', 'Success'), ('failed', 'Failed')], default='initiated', max_length=20),
        ),
    ]
